### ISSUE TITLE
Game crashes when starts up

### ISSUE THREAD

**Issue by CKTheUltimate** [pcr3w/JsCraft-Wiki#1]
I tried bot version uploaded on curse forge,but none of them works...
Crash report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/20/16 9:54 PM
Description: Initializing game

java.lang.IllegalStateException
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:268)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:254)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:222)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:208)
	at com.pcr3w.jscraft.proxies.CommonProxy.preInit(CommonProxy.java:35)
	at com.pcr3w.jscraft.core.JsCraft.preInit(JsCraft.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:268)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:254)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:222)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:208)
	at com.pcr3w.jscraft.proxies.CommonProxy.preInit(CommonProxy.java:35)
	at com.pcr3w.jscraft.core.JsCraft.preInit(JsCraft.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105046800 bytes (100 MB) / 289173504 bytes (275 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCH	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCE	jscraft{0.2.0} [JsCraft] (jscraft-0.2.0.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-10.12.13, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz

**Comment by p-crew** [comment]
Have you tried updating and changing your Java version to the latest 1.8 update (http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)?

**Comment by p-crew** [comment]
I'm afraid I'll have to assume this issue has been solved if you do not reply in 2 days time.

**Comment by CKTheUltimate** [comment]
I still can't get the game start up,I already have the latest version of java.

**Comment by p-crew** [comment]
The crash report says Java 1.8.0_74, have you tried a later version (1.8.0_91, etc)?

**Comment by OcAMD** [comment]
I had the same issues with both the 2.0 and the 2.0.1 versions. This is the 2.0 crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  BCModPlugin (zz-backpacks 1.8.9 - 3.1.3.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 11/25/16 4:38 PM
XRay version: 35
Description: Initializing game

java.lang.IllegalStateException
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:268)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:254)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:222)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:208)
	at com.pcr3w.jscraft.proxies.CommonProxy.preInit(CommonProxy.java:35)
	at com.pcr3w.jscraft.core.JsCraft.preInit(JsCraft.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:268)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:254)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:222)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:208)
	at com.pcr3w.jscraft.proxies.CommonProxy.preInit(CommonProxy.java:35)
	at com.pcr3w.jscraft.core.JsCraft.preInit(JsCraft.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 627162568 bytes (598 MB) / 1387589632 bytes (1323 MB) up to 3194421248 bytes (3046 MB)
	Mod Pack: LiteLoader startup failed
	LiteLoader Mods: LiteLoader startup failed
	LaunchWrapper: 32 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: net.minecraftxray.loader.l
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.codechicken.lib.asm.ClassHeirachyManager
          - Transformer: $wrapper.codechicken.lib.asm.RenderHookTransformer
          - Transformer: $wrapper.net.fybertech.nwr.NowWithRendering
          - Transformer: $wrapper.net.fybertech.nwr.NowWithRendering
          - Transformer: $wrapper.brad16840.common.asm.ClassTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: $wrapper.com.github.parker8283.bif.Transformer
          - Transformer: $wrapper.com.olafski.fastleafdecay.FldTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256M -Xms1G -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: Minecraft 1.8.9 MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H6 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCH	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCH	backpacks16840{3.1.3} [Backpacks!] (zz-backpacks 1.8.9 - 3.1.3.jar) 
	UCH	bowinfinityfix{rv2} [Bow Infinity Fix] (minecraft.jar) 
	UCH	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCH	woodconverter{v2.8_3} [Wood Converter] ([1.8.8]WoodConverter v2.8_3.jar) 
	UCH	net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.0} [CutAllSMP] ([1.8.9][forge1742]mod_CutAllSMP_v2.5.0.zip) 
	UCH	movillages{1.5.1} [Mo' Villages] ([1.8.x]Mo' Villages-1.5.1.jar) 
	UCH	adobeblocks{4.1.1.10} [Adobe Blocks] (AdobeBlocks-4.1.1.10.jar) 
	UCH	adobeblocksvc{1.5} [Adobe Blocks 2 Version Checker] (AdobeBlocks-4.1.1.10.jar) 
	UCH	cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.9.jar) 
	UCH	cfmce{1.0.1} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0.1-mc1.8.9.jar) 
	UCH	Chameleon{1.8.9-1.1.5} [Chameleon] (Chameleon-1.8.9-1.1.5.jar) 
	UCH	ChestTransporter{2.2.1} [Chest Transporter] (ChestTransporter-2.2.1-MC1.8.9.jar) 
	UCH	lootablebodies{1.4.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.0.jar) 
	UCH	drpcore{0.1.3c} [Dark Roleplay Core] (Dark Roleplay Core 0.1.3c.jar) 
	UCH	drpmedieval{0.1.2c} [Dark Roleplay Medieval] (Dark Roleplay Medieval - 1.8.9 - 0.1.2c.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.5_1.8.9.jar) 
	UCH	props{2.3.4} [Decocraft] (Decocraft-2.3.5_1.8.9.jar) 
	UCH	decorationmegapack{1.8.9.2} [Decoration Mega Pack] (decorationmegapack-1.8.9.2.jar) 
	UCH	thebombzenapi{2.5.2} [ThebombzenAPI] (ThebombzenAPI-v2.5.2-mc1.8.9.jar) 
	UCH	enchantview{5.0.1} [EnchantView] (EnchantView-v5.0.1-mc1.8.9.jar) 
	UCH	endercompass{1.2.2.1} [Ender Compass] (EnderCompass-1.8.x-1.2.2.1.jar) 
	UCH	excore{1.5.3} [EXCore] (Excore-1.5.3-1.8.9.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCH	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCH	llor{1.0.7-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.8.9.jar) 
	UCH	FEI{1.0.10} [Forever Enough Items] (ForeverEnoughItems-1.0.10-1.8.9.jar) 
	UCH	furnus{1.75} [Furnus] (Furnus-1.8.9-1.75.jar) 
	UCH	Harvest{1.8.9-1.0.0-2} [Harvest] (Harvest-1.8.9-1.0.0-2.jar) 
	UCH	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCE	jscraft{0.2.0} [JsCraft] (jscraft-0.2.0.jar) 
	UCH	bonecraft{1.8.9a} [Pam's BoneCraft] (Pam's BoneCraft 1.8.9a.jar) 
	UCH	PigManure{1.0.1} [Pig Manure] (pig-manure-1.0.1-mc1.8.9.jar) 
	UCH	pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.8.9-1.5.0.jar) 
	UCH	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCH	AS_Ruins{15.6} [Ruins Spawning System] (Ruins-1.8.8.jar) 
	UCH	simplegrinder{0.150.R} [Simple Grinder] (SimpleGrinder-0.150.R189.jar) 
	UCH	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.8-2.1.jar) 
	UCH	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.1 - 1.8.9.jar) 
	UCH	StorageDrawers{1.8.9-2.6.6} [Storage Drawers] (StorageDrawers-1.8.9-2.6.6.jar) 
	UCH	tellme{0.2.9} [Tell Me] (tellme-1.8.9-0.2.9.jar) 
	UCH	thelittlethings{1.2.4} [The Little Things] (The Little Things-v.1.2.4-mc1.8.9.jar) 
	UCH	villagebox{1.8.9-0.4.0} [Village Box] (villagebox-1.8.9-0.4.0.jar) 
	UCH	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.8-2.1.jar) 
	UCH	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCH	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	UCH	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCH	YALSM{2.1.5} [Yet Another Leather Smelting Mod] (yalsm-2.1.5-mc1.8.9.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
BCModPlugin (zz-backpacks 1.8.9 - 3.1.3.jar)
  brad16840.common.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  com.github.parker8283.bif.Transformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Misa.zip, XDBMisaPatchV1.4.zip, Misa Patch Les 1.8.zip, [1.7.10]Delta-NP Backpacks 64x64.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 745/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by p-crew** [comment]
Have you tried changing your Java version to a later 1.8.0 build as your's is 1.8.0_11?

**Comment by OcAMD** [comment]
Please take a closer look.

-- System Details --
Details:
![javaversion](https://cloud.githubusercontent.com/assets/23746844/20637606/f7f51dcc-b35a-11e6-8227-a61dcb1d1ae4.png)

Minecraft Version: 1.8.9
Operating System: Windows 8.1 (amd64) version 6.3
CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
**Java Version: 1.8.0_111, Oracle Corporation**
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 627162568 bytes (598 MB) / 1387589632 bytes (1323 MB) up to 3194421248 bytes (3046 MB)

**Comment by daniel359davidson** [comment]
Still crashes with the same console output.
Used both 1.8.0_111 and 1.8.0_91 JRE version.

**Comment by dattosma** [comment]
Same issue on my system:
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCH	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCE	jscraft{0.2.0} [JsCraft] (jscraft-0.2.0.1.jar) 
Java Version: 1.8.0_111, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

**Comment by p-crew** [comment]
~~I've uploaded a potential fix for the crash to the mod site (it's currently under review). Please get back to me and tell me if it works as I cannot replicate the crash myself.~~

The issue can be fixed by changing your Java version to a development kit (JDK - you can find a compatible one [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)).

**Comment by p-crew** [comment]
Sorry I haven't replied sooner - I've had a busy Christmas.

**Comment by p-crew** [comment]
I've found the issue. The Java version needs to be **the Development Kit** - I'll make sure that that is more clear.

**Comment by p-crew** [comment]
If this issue has no more replies in the next 2 days then I'll assume it to be fixed.

**Comment by daniel359davidson** [comment]
Still crash.
JDK 8 update 111

Crashlog: http://pastebin.com/YCghTjVQ

**Comment by p-crew** [comment]
And you definitely changed the version in the launcher profile?

**Comment by daniel359davidson** [comment]
My bad. After changing Java launch path to "C:\Program Files\Java\jdk1.8.0_111\bin\javaw.exe" (i use 64-bit version) game launched normaly.
Thanks for fix and thanks for the mod!

**Comment by p-crew** [comment]
No problem :)
Feel free to report any more issues that you encounter. I'll mark this as closed - if it still crashes for anyone then please report it as a new issue and refer to this one.
